compute_environment: LOCAL_MACHINE
deepspeed_config:
  # deepspeed_config_file: deepspeed.yaml
  gradient_accumulation_steps: 4 #! Keep consistent with external parameters
  gradient_clipping: 0.5 #! Keep consistent with external parameters
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 5 #! Number of GPUs
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
